//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public Nullable<int> TaskId { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<System.DateTime> Uploaded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Id { get; set; }
    
        public virtual ProjectTasks ProjectTasks { get; set; }
    }
}
