//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRoles
    {
        public Nullable<int> ProjectId { get; set; }
        public string RoleId { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
