//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskHistory
    {
        public int TaskId { get; set; }
        public string UserId { get; set; }
        public System.DateTime ChangedOn { get; set; }
        public Nullable<System.DateTime> EstimatedEndsOn { get; set; }
        public string AssignedUserId { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> EndedOn { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Description { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual ProjectTasks ProjectTasks { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskTypes TaskTypes { get; set; }
    }
}
