//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTasks()
        {
            this.Comments = new HashSet<Comments>();
            this.Files = new HashSet<Files>();
            this.ProjectTaskHistory = new HashSet<ProjectTaskHistory>();
            this.ProjectTasks1 = new HashSet<ProjectTasks>();
            this.UserBoardTasks = new HashSet<UserBoardTasks>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime StartedOn { get; set; }
        public Nullable<System.DateTime> EndedOn { get; set; }
        public string Url { get; set; }
        public int StatusId { get; set; }
        public int TaskTypeId { get; set; }
        public string AssignedUserId { get; set; }
        public Nullable<System.DateTime> EstimatedEndsOn { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Files> Files { get; set; }
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTaskHistory> ProjectTaskHistory { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskTypes TaskTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTasks> ProjectTasks1 { get; set; }
        public virtual ProjectTasks ProjectTasks2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBoardTasks> UserBoardTasks { get; set; }
    }
}
